networks:
  db-net:
    driver: bridge

services:
  rtmp:
    build: ./rtmp
    container_name: YKRTMP
    ports:
      - "1935:1935"
    volumes:
      - /var/www/streams:/var/www/streams
      - /var/www/vods:/var/www/vods
    depends_on:
      - api
    networks:
      - db-net
  portal:
    build: ./portal
    container_name: YKStreamingPortal
    volumes:
      - /var/www/thumbnails:/var/www/thumbnails
      - /var/www/streams:/var/www/streams
      - /var/www/vods:/var/www/vods
    ports:
      - "5173:5173"
      - "80:80"
    depends_on:
      - api
    networks:
      - db-net
  db-primary:
    build: ./db-primary
    container_name: YKDBPRIMARY
    networks:
      - db-net
    environment:
      POSTGRES_USER: babylon
      POSTGRES_PASSWORD: SofSvi_37
      POSTGRES_DB: ykstreaming
    volumes:
      - ./db-primary/data:/var/lib/postgresql/data
      - ./db-primary/init:/docker-entrypoint-initdb.d
  db-replica:
    build: ./db-replica
    container_name: YKDBREPLICA
    networks:
      - db-net
    environment:
      POSTGRES_USER: babylon
      POSTGRES_PASSWORD: SofSvi_37
      POSTGRES_DB: ykstreaming
    volumes:
      - ./db-replica/data:/var/lib/postgresql/data
      - ./db-replica/init:/docker-entrypoint-initdb.d
  api:
    build: ./api
    container_name: YKAPI
    volumes:
      - /var/www/thumbnails:/var/www/thumbnails
      - /var/www/streams:/var/www/streams
      - /var/www/vods:/var/www/vods
    depends_on:
      - db-primary
      - db-replica
    networks:
      - db-net
