networks:
  default:
    name: YK_DEFAULT_NETWORK
    driver: bridge

services:
  rtmp:
    build: ./rtmp
    container_name: YK_RTMP
    ports:
      - "1935:1935"
    volumes:
      - /var/www/streams:/var/www/streams
      - /var/www/vods:/var/www/vods
    depends_on:
      - api
    networks:
      - default
  portal:
    build: ./portal
    container_name: YK_WEB_PORTAL
    volumes:
      - /var/www/thumbnails:/var/www/thumbnails
      - /var/www/streams:/var/www/streams
      - /var/www/vods:/var/www/vods
    ports:
      - "5173:5173"
      - "80:80"
    depends_on:
      - api
    networks:
      - default
  etcd-1:
    build: ./etcd-1
    container_name: YK_ETCD_1
    networks:
      - default
  etcd-2:
    build: ./etcd-2
    container_name: YK_ETCD_2
    networks:
      - default
    depends_on:
      - etcd-1
  etcd-3:
    build: ./etcd-3
    container_name: YK_ETCD_3
    networks:
      - default
    depends_on:
      - etcd-1
      - etcd-2
  db-1:
    build: ./db-1
    container_name: YK_DB_1
    networks:
      - default
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    volumes:
      - db_1_data:/var/lib/postgresql/data
  db-2:
    build: ./db-2
    container_name: YK_DB_2
    networks:
      - default
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    volumes:
      - db_2_data:/var/lib/postgresql/data
  db-3:
    build: ./db-3
    container_name: YK_DB_3
    networks:
      - default
    depends_on:
      - etcd-1
      - etcd-2
      - etcd-3
    volumes:
      - db_3_data:/var/lib/postgresql/data
  db-manager:
    build: ./db-manager
    container_name: YK_DB_MANAGER
    depends_on:
      - db-1
      - db-2
      - db-3
    networks:
      - default
  api:
    build: ./api
    container_name: YK_API
    volumes:
      - /var/www/thumbnails:/var/www/thumbnails
      - /var/www/streams:/var/www/streams
      - /var/www/vods:/var/www/vods
    depends_on:
      - db-manager
    networks:
      - default

volumes:
  db_1_data:
    name: YK_DB_1_VOLUME
  db_2_data:
    name: YK_DB_2_VOLUME
  db_3_data:
    name: YK_DB_3_VOLUME
