name: 'etcd-2'
initial-advertise-peer-urls: http://etcd-2:2380

listen-peer-urls: http://0.0.0.0:2380
listen-client-urls: http://0.0.0.0:2379

advertise-client-urls: http://etcd-2:2379
initial-cluster: "etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380"
initial-cluster-token: 'patroni-cluster'
initial-cluster-state: 'new'